# Generated by Django 2.2.5 on 2019-12-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sema', '0054_relevancy_exception'),
    ]

    operations = [
        migrations.AddField(
            model_name='semadescriptionpiesattribute',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='brand has given access to dataset'),
        ),
        migrations.AddField(
            model_name='semadescriptionpiesattribute',
            name='is_relevant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semadescriptionpiesattribute',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
        migrations.AddField(
            model_name='semadigitalassetspiesattribute',
            name='is_authorized',
            field=models.BooleanField(default=False, help_text='brand has given access to dataset'),
        ),
        migrations.AddField(
            model_name='semadigitalassetspiesattribute',
            name='is_relevant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semadigitalassetspiesattribute',
            name='relevancy_exception',
            field=models.CharField(blank=True, max_length=255, verbose_name='exception'),
        ),
    ]
